name: github pages

on:
  schedule:
    - cron: '0 0 * * *' # Auto-trigger workflow everyday at 00:00
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dependencies
        run: |
          echo "Preparing Orca"
          ./scripts/get-cee-utils.sh
          echo "Preparing Orca-Docs"
          git clone https://github.com/cee-studio/orca-docs
          cp orca-docs/Doxyfile Doxyfile
          echo "Install Sphinx"
          pip install sphinx
          pip install pydata_sphinx_theme
          echo "Install Breathe"
          pip install breathe

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1

      - name: Move XML to Orca-Docs
        run: sudo mv docs/xml orca-docs/docs

      - name: Breathe Action
        run: make -C orca-docs/docs html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./orca-docs/docs/build/html
